CREATE TABLE gov.Holding(
 HoldingId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 Nome NVARCHAR(200) NOT NULL,
 Sigla NVARCHAR(20) NOT NULL UNIQUE,
 Status VARCHAR(20) NOT NULL CHECK(Status IN ('Active','Inactive'))
);
GO
CREATE TABLE gov.Company(
 CompanyId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 HoldingId UNIQUEIDENTIFIER NOT NULL,
 Nome NVARCHAR(200) NOT NULL,
 Sigla NVARCHAR(20) NOT NULL UNIQUE,
 CNPJ VARCHAR(14) NOT NULL UNIQUE,
 Status VARCHAR(20) NOT NULL CHECK(Status IN ('Active','Inactive')),
 CONSTRAINT FK_Company_Holding FOREIGN KEY(HoldingId) REFERENCES gov.Holding(HoldingId)
);