CREATE TABLE sec.[User](
 UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 EntraObjectId UNIQUEIDENTIFIER NOT NULL UNIQUE,
 Email NVARCHAR(255) NOT NULL UNIQUE,
 DisplayName NVARCHAR(200) NOT NULL,
 CompanyId UNIQUEIDENTIFIER NOT NULL,
 IsActive BIT NOT NULL CONSTRAINT DF_User_IsActive DEFAULT(1)
);